language: java 
jdk: oraclejdk8
node_js:
  - "6"
addons:
  sonarqube: true
env:
  global:
    - secure: "KMblETODabQXvnRlFwM4lQOjQhr2A5hhMPRjydLWI2yDn0v/zP6M1hL1UPUDnAfw5Pvf6Fdn0j5ehR0CrRunfsE2Hk3/CJGly9W00B+87K0ptqWqgVxSNq7JwdrhgQjM7I6VOhOqr6GCOLwdUhBN8zLI0wprn12LY7m4zxTLZ71hNT7Kgn6D/GIM6yG+rOnRwnvq8l941TwQQCbdxa7qf9LvCQ6hZDXB6W4i8T+0pI5Y0EByCniddVl1Zivs4fWsfVD+vYkXJt241UIjptb8g0jTaSkowJiaglRaKV0p3ndF5EQxysNzlwC3Zp47bnPapr8IEjsMo1oJVhPa3ywa3/zvfGsXsQ8TM9bdT5FN6HPLcKzlA35TKN9/4OyZGdPC4g1hINh51EE7AlIGQ1lidw5iSSIerTlD7IP8ACn+ZYoTdfbefXBn04X7IwtCTI7D9/w0dC1+dLaYjBWLzYQmzr/GcLyiqf0jdpjq9qEXEyi/97HUQWlmHLh/donRjmCZ3Cx4cg/3/V4KYf/xT7rTUXt7PkCy18rt60I3IDvxnJO1hjD8Eh7qomNcu0n4ecc7QP2oWxDLR9bCvdEE288s8/DbHA3Ra9dYLJWGhBGfOi7v8Q4DOX0x7pKGfmHNkV2CEFYVLCA5FpxoXcUyA+3kTjmoMyWh7+ZjPhBhMNDI6vk="
script:
  - sonar-scanner -Dsonar.login=$SARAN__SONAR_TOKEN
